name: Login

on:
  push:
    branches: master

jobs:
  login:
    runs-on: windows-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v1.9.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
